package com.medbook.appointment.saga;

public enum SagaEventType {
    DOCTOR_RESERVE_COMMAND,
    ROOM_SLOT_RESERVE_COMMAND,
    EQUIPMENT_SLOT_RESERVE_COMMAND,
    DOCTOR_RELEASE_COMMAND,
    ROOM_SLOT_RELEASE_COMMAND,
    EQUIPMENT_SLOT_RELEASE_COMMAND,
    DOCTOR_RESERVED,
    DOCTOR_RESERVE_FAILED,
    ROOM_SLOT_RESERVED,
    ROOM_SLOT_RESERVE_FAILED,
    EQUIPMENT_SLOT_RESERVED,
    EQUIPMENT_SLOT_RESERVE_FAILED,
    DOCTOR_RELEASED,
    DOCTOR_RELEASE_FAILED,
    ROOM_SLOT_RELEASED,
    ROOM_SLOT_RELEASE_FAILED,
    EQUIPMENT_SLOT_RELEASED,
    EQUIPMENT_SLOT_RELEASE_FAILED,
    APPOINTMENT_BOOKED,
    APPOINTMENT_CANCELLED
}
